// Real player face art from the sofifa (FIFA/FC) CDN, keyed by the exact name
// used in players.ts. Only IDs verified to resolve on FC26 are included; every
// avatar has an onError fallback, so any miss degrades gracefully.
//
// URL pattern: https://cdn.sofifa.net/players/<first3>/<next3>/26_120.png
// where the numeric id is zero-padded to 6 digits and split 3/3.

const SOFIFA_ID: Record<string, number> = {
  // Argentina
  "L. Messi": 158023,
  "E. Martínez": 220834,
  // France
  "K. Mbappé": 231747,
  "O. Dembélé": 231443,
  "W. Saliba": 246804,
  "A. Tchouaméni": 241486,
  "E. Camavinga": 247635,
  // Spain
  "Rodri": 231866,
  "Pedri": 251854,
  "Lamine Yamal": 277643,
  // England
  "H. Kane": 202126,
  "J. Bellingham": 252371,
  "P. Foden": 237692,
  "B. Saka": 246669,
  "Declan Rice": 234378,
  // Brazil
  "Alisson": 212831,
  "Marquinhos": 207865,
  "Vinícius Jr": 238794,
  // Portugal
  "Cristiano Ronaldo": 20801,
  "Bruno Fernandes": 212198,
  "Rúben Dias": 239818,
  "Rafael Leão": 241721,
  // Netherlands
  "V. van Dijk": 203376,
  "F. de Jong": 228702,
  // Germany
  "J. Kimmich": 212622,
  "M. ter Stegen": 192448,
  "A. Rüdiger": 205452,
  "Jamal Musiala": 256790,
  "F. Wirtz": 256630,
  // Belgium
  "K. De Bruyne": 192985,
  "R. Lukaku": 192505,
  // Croatia
  "L. Modrić": 177003,
  // Korea
  "Son Heung-min": 200104,
  // Senegal
  "S. Mané": 208722,
  // Colombia
  "J. Rodríguez": 198710,
  // Switzerland
  "G. Xhaka": 186345,
  // Norway
  "M. Ødegaard": 224334,
  "E. Haaland": 239085,
  // Morocco
  "A. Hakimi": 235212,
};

function sofifaUrl(id: number): string {
  const s = String(id).padStart(6, "0");
  return `https://cdn.sofifa.net/players/${s.slice(0, 3)}/${s.slice(3, 6)}/26_120.png`;
}

// Auto-resolved photos from TheSportsDB (validated: sport+nationality+initial).
// Generated by scripts/fetch-photos.mjs.
import GENERATED from "./playerPhotos.generated.json";
const GEN = GENERATED as Record<string, string>;

// Priority: hand-verified sofifa (FIFA face art) → auto-resolved → none (fallback).
export function playerPhoto(name: string): string | null {
  const id = SOFIFA_ID[name];
  if (id) return sofifaUrl(id);
  return GEN[name] ?? null;
}
